# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassificadorTerra
                                 A QGIS plugin
 Este complemento classifica pontos com base em suas características geofísicas e geológicas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-26
        copyright            : (C) 2024 by Gabriel G.R. de Lima
        email                : gabrielgoes@usp.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClassificadorTerra class from file ClassificadorTerra.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .classificador_terra import ClassificadorTerra
    return ClassificadorTerra(iface)
