# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mapgeo
                                 A QGIS plugin
 Plugin para aprimorar tecnica de mapeamento geologico
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-15
        copyright            : (C) 2024 by Intelli+geo
        email                : gabrielgoes@usp.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mapgeo class from file mapgeo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mapgeo import mapgeo
    return mapgeo(iface)
