# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PreditorTerra
                                 A QGIS plugin
 Sistema cibernetico de producao de mapas geologicos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-11
        copyright            : (C) 2025 by gabriel
        email                : garielgoes@usp.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PreditorTerra class from file PreditorTerra.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .preditor_terra import PreditorTerra
    return PreditorTerra(iface)
