> pdflatex RP_IC_GGRL_16_03_2021_Revisado.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./RP_IC_GGRL_16_03_2021_Revisado.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-20>
(/usr/share/texmf-dist/tex/latex/base/iagtese.cls
Document Class: iagtese 18/06/2010 versao 2.15 Classe LaTeX para teses IAG/USP
(/usr/share/texmf-dist/tex/latex/base/bk12.clo)
(/usr/share/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texmf-dist/tex/generic/iftex/ifvtex.sty
(/usr/share/texmf-dist/tex/generic/iftex/iftex.sty)))
(/usr/share/texmf-dist/tex/latex/epstopdf-pkg/epstopdf.sty
(/usr/share/texmf-dist/tex/generic/infwarerr/infwarerr.sty)
(/usr/share/texmf-dist/tex/latex/grfext/grfext.sty
(/usr/share/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty))
(/usr/share/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/share/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texmf-dist/tex/latex/kvsetkeys/kvsetkeys.sty))
(/usr/share/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty)
(/usr/share/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty

Package epstopdf Warning: No graphics package `graphic{s,x}' loaded.

)) (/usr/share/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texmf-dist/tex/generic/babel/txtbabel.def)
(/usr/share/texmf-dist/tex/generic/babel-portuges/brazilian.ldf))
(/usr/share/texmf-dist/tex/generic/babel/locale/pt/babel-brazilian.tex)
(/usr/share/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texmf-dist/tex/latex/base/latin1.def))
(/usr/share/texmf-dist/tex/latex/graphics/epsfig.sty
(/usr/share/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texmf-dist/tex/latex/graphics-def/pdftex.def))))
(/usr/share/texmf-dist/tex/latex/float/float.sty)
(/usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texmf-dist/tex/latex/amsfonts/amsfonts.sty)
(/usr/share/texmf-dist/tex/latex/base/latexsym.sty)
(/usr/share/texmf-dist/tex/latex/amscls/amsthm.sty)
(/usr/share/texmf-dist/tex/latex/tools/multicol.sty)
(/usr/share/texmf-dist/tex/latex/tools/indentfirst.sty)
(/usr/share/texmf-dist/tex/latex/amsfonts/amssymb.sty)
(/usr/share/texmf-dist/tex/latex/base/bibliografia.sty)
(/usr/share/texmf-dist/tex/latex/base/deluxetable.sty)
(/usr/share/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texmf-dist/tex/latex/caption/caption.sty
(/usr/share/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/share/texmf-dist/tex/latex/base/fancyhdr.sty)
(/usr/share/texmf-dist/tex/generic/dvips/colordvi.tex)

Package Fancyhdr Warning: \fancyhead's `E' option without twoside option is use
less on input line 1434.


Package Fancyhdr Warning: \fancyhead's `E' option without twoside option is use
less on input line 1435.

) (/usr/share/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./RP_IC_GGRL_16_03_2021_Revisado.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texmf-dist/tex/latex/ragged2e/ragged2e.sty) (./tex/capa.tex)
(/usr/share/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/usr/share/texmf-dist/tex/latex/base/ulasy.fd) [1{/var/lib/texmf/fonts/map/pdf
tex/updmap/pdftex.map}] [2] [3] (./tex/resumo.tex
! Missing $ inserted.
<inserted text>
                $
l.1 ...as de IA têm uma enorme gama de aplicaçõ
                                                  es nas mais diversas área...

?
